ch_cookie_consent:
  theme: 'dark' # light, dark
  categories: # Below are the default supported categories
    - 'analytics'
    - 'tracking'
  use_logger: true # Logs user actions to database
  position: 'top' # top, bottom
  simplified: false # When set to true the user can only deny or accept all cookies at once
  http_only: true # Sets HttpOnly on cookies